###########
# site.url, site.title

url:   'http://felixeye.github.io/'
title: 'TEST SciLifeLab Courses'
#google_analytics: 'UA-23985298-11'


########
# more settings

# Setup
title:               Courses
tagline:             ScilifeLab course
#url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# markdown: redcarpet
# highlighter: pygments
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

markdown: redcarpet
pygments: true

sass:
  #sass_dir: css
  sass_dir: _sass
  style:    expanded



exclude:
- README.md

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/hfixou
  email:             felixhoma@yahoo.fr

safe: true
lsi: false
